name: deploy-node
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/myapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with: 
          node-version: '14.x'
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 4.4
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test